<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<script>
    //第一种写法
    // new Promise((resolve,reject) => {
    //     setTimeout(() => {
    //         resolve('aaa')
    //     }, 1000);
    // }).then((res) =>{
    //     console.log(res)
    //     return new Promise((resolve,reject) => {
    //         resolve(res + '111')
    //     })
    // }).then((res) => {
    //     console.log(res)
    //     return new Promise((resolve,reject) => {
    //         resolve(res + '222')
    //     })
    // }).then((res) => {
    //     console.log(res)
    // })

    //第二种写法(简写)
    // new Promise((resolve,reject) => {
    //     setTimeout(() => {
    //         resolve('aaa')
    //     }, 1000);
    // }).then((res) =>{
    //     console.log(res)
    //     return Promise.resolve(res + '111')
    // }).then((res) => {
    //     console.log(res)
    //     return Promise.resolve(res + '222')
    // }).then((res) => {
    //     console.log(res)
    // })

    //第三种写法(简写)
    // new Promise((resolve,reject) => {
    //     setTimeout(() => {
    //         resolve('aaa')
    //     }, 1000);
    // }).then((res) =>{
    //     console.log(res)
    //     return res + '111'
    // }).then((res) => {
    //     console.log(res)
    //     return res + '222'
    // }).then((res) => {
    //     console.log(res)
    // })

    //里面有抛出异常的写法
    // new Promise((resolve,reject) => {
    //     setTimeout(() => {
    //         resolve('aaa')
    //     }, 1000);
    // }).then((res) =>{
    //     console.log(res)
    //     return Promise.reject('error')
    // }).then((res) => {
    //     console.log(res)
    //     return res + '222'
    // }).then((res) => {
    //     console.log(res)
    // }).catch((err) => {
    //     console.log(err)
    // })

    //里面有异常的第二种写法
    new Promise((resolve,reject) => {
        setTimeout(() => {
            resolve('aaa')
        }, 1000);
    }).then((res) =>{
        console.log(res)
        throw 'error'
    }).then((res) => {
        console.log(res)
        return res + '222'
    }).then((res) => {
        console.log(res)
    }).catch((err) => {
        console.log(err)
    })
</script>
</body>
</html>
